<?php 
    return [
        'privacyPolicyTitle'=>'Privacy Policy',
        'privacyPolicyContent'=>'
            <cite>Effective date: August 2020</cite><br><br>
            <p>Welcome to Chep.xyz This Privacy Policy describes the policies and procedures of Chep.xyz . (“Chep.xyz”, “we” or “us”) on the collection, use, security and disclosure of personal information about you on https://Chep.xyz (the “Site”) and the services, features, content or applications offered by Chep.xyz (collectively with the Site, the “Services”). It also describes your choices regarding use, access and correction of your personal information.</p>
                <h3>Scope</h3>
                <p>
                This Privacy Policy covers the treatment of the personal information gathered by Chep.xyz when you use or access the Services, or when you view or interact with a Chep.xyz link (either our bit.ly links of one of our branded domains). This Privacy Policy also covers Chep.xyz’s treatment of any information about you that Chep.xyz’s customers share with Chep.xyz.</p>
                <p>
                This Privacy Policy does not apply to the practices of other businesses that Chep.xyz does not own or control, including other companies’ websites, services and applications (“Third Party Services”) that you can access through the Services, such as Facebook or Twitter, or to individuals that Chep.xyz does not manage or employ. We cannot take responsibility for the content or privacy policies of those Third Party Services. We encourage you to review the privacy policies of any Third Party Services you access.</p>
                Information We Collect
                <p>
                Chep.xyz may collect personal information about you as described in this Privacy Policy when you (i) register for the Site and the Services, through your user account with Chep.xyz, including registering through a third-party social networking service (your “Account”), (ii) use the Services, or (iii) view or interact with a Chep.xyz link (either our bit.ly links or one of our branded domains) on a third-party website. We collect the following types of information from you, some of which might be considered personal information under applicable law.</p>
                
                <h3>When You Register for a Chep.xyz Account</h3>
                <p>
                When you create an Account, we may collect personal information from you, such as your name, phone number, company name, industry, job title, company size and email address. If you create an Account using your login from a third-party account, such as Google, Facebook or Twitter, we will access and collect the personal information about you that the third-party account provides (which is based on your privacy settings with the third-party account), so that you can log into your Account with us. We use your contact information to send you information about our Services and communicate with you about your Account, your activities on our Site and Services and policy changes. You may unsubscribe from receiving certain types of these messages through your Account settings, although Chep.xyz reserves the right to contact you when we believe it is necessary, such as for administrative and account management purposes.</p>
                <p>
                Some features of the Services allow registered users to provide their own content to the Services, such as written descriptions of URLs, comments, images and video. Unless you request deletion of your personal information as described in this Privacy Policy, all content submitted by you to the Services may be retained by Chep.xyz, even after you terminate your Account and may continue to be shared by third parties, as described in this Privacy Policy.</p>
                
                <h3>When You Create a Chep.xyz Link</h3>
                <p>
                One feature of the Services is the ability to create shortened uniform resource locators (URLs) of websites (“Chep.xyz Link” or “Bitlinks”). Users can create Chep.xyz Links without registering for an account.  When you create a Chep.xyz Link, Chep.xyz collects and stores both the original URL and the shortened URL and, if you are logged in to your Account, we will associate that information with your Account. Chep.xyz also collects and stores your IP address, your location, which we derive from your IP address, the time and date on which you shortened the original URL, and if you share a Chep.xyz Link on a social networking platform, the name of the platform and your username on that platform.</p>
                
                <h3>When You Interact With a Chep.xyz Link</h3>
                <p>
                Chep.xyz automatically collects personal information about the interaction (such as clicks or views) with every Chep.xyz Link created through the Services (either our bit.ly links or one of our branded domains) on a third-party website. This information includes, but is not limited to: (i) the IP address and location derived from the IP address; (ii) the referring websites or services; (iii) the time and date of each access; (iv) device settings, such as browser type, operating system, and language; (v) cookies, as described below, and mobile advertising identifiers and (v) information about sharing of the Chep.xyz Link on Third Party Services such as Twitter and Facebook (collectively, “Chep.xyz Link Metrics”).  As described in this policy, we use Chep.xyz Link Metrics to provide the Services, to understand and analyze how our Services are used and to identify trends, and to detect, deter and prevent malicious, fraudulent or unlawful activity. Please see the “Information We May Share” section of this Privacy Policy for a description of how we may share information we collect when you create, view or interact with Chep.xyz Links.</p>
                
                <h3>Other Information We Automatically Collect</h3>
                <p>
                When you visit the Site, we automatically collect (i) your IP address and location derived from the IP address; (ii) the referring websites or services; (iii) the time and date of each access; (iv) device settings, such as browser type, operating system, and language; and (v) cookie information. This type of data enables us and third parties authorized by us to figure out how often individuals use parts of the Site so that we can analyze and improve them.</p>
                <p>
                We may receive a confirmation when you open an email from us. We use this confirmation to improve our customer service.
                </p>
                <p>
                Chep.xyz may use third-party APIs and software development kits (“SDKs”) to provide certain functions in our Services.
                </p>
                <h3>Third Party Services</h3>
                <p>
                Some features of the Services allow you to share your content and Chep.xyz Links through your accounts with other companies such as Facebook and Twitter. If you choose to connect Chep.xyz to such Third Party Services, we may collect information related to your use of those Third Party Services, such as authentication tokens that allow us to connect to your Third Party Service accounts. We will ask you for permission before you authorize our collection of this information. We will only use that information for the specific reason for which it was provided to us. We may also collect information about how you are using the Services to interact with those connected Third Party Services. Note that Third Party Services may have the ability to restrict the information that is provided to us based on your privacy settings of that account.</p>
                <p>
                To enable us to infer the location from the IP addresses of computers or devices that visit our website or click, view or interact with Chep.xyz links as described in this policy, we receive IP-based location information from our third-party service provider. We also receive business contact information of our business customer contacts and prospects from our third party service provider.</p>
                
                <h3>Cookies and Other Similar Technologies</h3>
                <p>
                Chep.xyz and its partners use cookies or similar technologies to analyze trends, administer the website, track users’ movements around the website, and to gather demographic information about our user base as a whole.</p>
                <p>
                Cookies are pieces of text that may be provided to your computer through your web browser when you access a website. Your browser stores cookies in a manner associated with each website you visit. We use cookies to enable our servers to recognize your web browser and tell us how and when you visit our Site and use the Services through the web.</p>
                <p>
                Chep.xyz cookies also allow Chep.xyz to track when you have clicked on a Chep.xyz Link. Each click of a Chep.xyz Link is tracked using a unique identifier assigned to you in one or more cookies stored by your web browser and associated with Chep.xyz. We may associate the unique identifier in our cookies with the other information we automatically collect when you use the Services, as described above, including your IP address, Chep.xyz Links you click, Chep.xyz Links you create, and information with your Account if you have one.</p>
                <p>
                Most browsers have an option for turning off the cookie feature, which will prevent your browser from accepting new cookies, as well as (depending on the sophistication of your browser software) allowing you to decide on acceptance of each new cookie in a variety of ways. If you disable cookies, you will not be able to use some features of the Services.</p>
                <p>
                We partner with third parties to track utilization and behavior on our websites, display advertising on our websites, and to manage our advertising on other sites. Our third-party partners may use cookies, web beacons, pixel tags or similar technologies in order to provide you advertising based upon your browsing activities and interests. If you wish to opt out of interest-based advertising click here or if located in the European Union click here.</p>
                <p>
                This Privacy Policy covers the use of cookies by Chep.xyz only and does not cover the use of cookies by any Third Party Services. Chep.xyz does not control when or how third parties place cookies on your computer, such as when you visit the website from a Chep.xyz Link. You can manage other companies’ cookies used for online advertising by visiting the Digital Advertising Alliance’s Consumer Choice Page.</p>
                
                <h3>Note Regarding Children</h3>
                <p>
                We do not knowingly collect personal information from children. If we learn that we have collected personal information of a child under 13 (or older as required by applicable law), we will take steps to delete such information from our files as soon as possible.</p>

                <h3>How We Use Information</h3>
                <p>
                We use the personal information we collect for a variety of administrative and business purposes to:
                </p>
                <ul>
                    <li>operate our Site and provide the Services,</li>
                    <li>process and complete any transactions,</li>
                    <li>verify individual identity,</li>
                    <li>respond to inquiries, questions and comments and provide customer and technical support,</li>
                    <li>provide access to certain functionalities of our Services,</li>
                    <li>personalize and improve the Services and develop new products and services,</li>
                    <li>to communicate with our current and prospective customers concerning our services,</li>
                    <li>measure interest and engagement in our Site and Services,</li>
                    <li>monitor and analyze usage and trends of the Site and Services,</li>
                    <li>provide services to our customers to allow them to understand how you interact with our Services and to help detect, deter and prevent malicious, fraudulent or unlawful activity,</li>
                    <li>comply with any legal obligations, and</li>
                    <li>enforce our terms and as otherwise described in this Privacy Policy.</li>
                </ul>
                <h3>Usage Across Devices</h3>
                <p>
                We may use the information we collect to make inferences that a unique individual has created or interacted with Chep.xyz links on different devices so that we can to detect, deter and prevent malicious, fraudulent or unlawful activity and analyze how users use our Services.  For example, if you created a Chep.xyz link on a computer connected to your residential WiFi network, and you soon thereafter clicked on a Chep.xyz link on a mobile device connected to the same WiFi network, we may infer that a single individual created and clicked on the Chep.xyz links because both events were associated with the same IP address in the same time period.</p>
                
                <h3>Other Legitimate Interests</h3>
                <p>
                We also may use personal information to pursue legitimate interests, such as direct marketing, research (including marketing research), network and information security, prevention of fraudulent, malicious and unlawful activities, or any other purpose disclosed to you at the time you provide personal information or allowed by law.</p>
                Information We Share
                <p>
                The Services are designed to help you share information with others. In addition, we provide Services to our Customers that use Chep.xyz Link Metrics.  As a result, some of the personal information generated through your use of the Services is shared publicly or with third parties as described below.</p>
                
                <h3>Chep.xyz Links You Create</h3>
                <p>
                Much of your activity on and through the Services is public by default. For example, when you create a Chep.xyz Link, the original URLs you have shortened and the corresponding Chep.xyz Links are publicly available.</p>
                
                <h3>Account Information</h3>
                <p>
                Where permitted by law, if you register a Chep.xyz Account with an email address on a domain owned by an organization, (for example, an employer or educational institution where you have an email account), we may share your email address and information about your Account, such as the number of links you have created, with that organization to explore the organization’s interest in creating or managing an enterprise account or for related purposes.</p>
                <p>
                The information you provide may be transferred, processed and/or accessed by us in the United States or another country where we (or our service providers) operate.</p>

                <h3>Retention</h3>
                <p>
                We retain the personal information we receive as described in this Privacy Policy for as long as you use our Services or as necessary to fulfill the purpose(s) for which it was collected, provide our Services, resolve disputes, establish legal defenses, conduct audits, pursue legitimate business purposes, enforce our agreements, and comply with applicable laws.
                Information Security</p>
                <p>
                Your Account information is protected by a password for your privacy and security. You can prevent unauthorized access to your Account by selecting and protecting your password appropriately, and limiting access to your computer and browser by signing off after you have finished accessing your Account.</p>
                <p>
                You don’t need an Account to create Chep.xyz Links, and you can use many of the features of the Services without registering, thereby limiting the type of information that is collected about you individually.</p>
                <p>
                Chep.xyz acknowledges that you have the right to access your personal information that we collect and are able to associate with you. If you have a Chep.xyz Account, you may access, correct, or request deletion of your personal information by logging into your Account.  Once logged in to your account, you will be able to view a history of the URLs you have shortened and the metrics pages for those URLs. You can request a complete copy of the personal information we store about your account by clicking the Request GDPR SAR Report button in your Account Settings.  For more information on how to request access to your information, please see our help article. You can delete your Account at any time through your Account settings page. If you delete your Account, you will no longer be able to access or use the Services. If you have an Account but are unable to access it, you can contact us at support@Chep.xyz.com. We will respond to your request within a reasonable timeframe. If you are a resident of the EEA or Switzerland, you have the right to ask that your personal data be corrected, updated, or erased. You may also have the right to object to, or request that we restrict, certain processing. If you would like to exercise any of these rights, you may contact us as indicated in the “Questions” section below. In certain circumstances, we may be required by law to retain your personal information.</p>
                <p>
                If you do not have a Chep.xyz account, Chep.xyz has no way of identifying you or verifying that you created or clicked on a Chep.xyz link.</p>
                <p>
                Please note that in the interest of ensuring that existing Chep.xyz Links continue to function for all of our users, the Chep.xyz Links that you have created and shared cannot be deleted or disabled (even if your Account is deleted), and any shortening and sharing activity that has already occurred on your Account also cannot be deleted. If you have concerns about any unauthorized use of your Account, you can delete your account within your Account settings.</p>
                <p>
                Please see the Cookie section above for additional choices you may have.
                </p>
                <h3>Changes to This Privacy Policy</h3>
                <p>
                Chep.xyz may amend this Privacy Policy from time to time. If we make material changes in the way we collect or use information, we will notify you by posting an announcement on the Services or sending you an email, and we will indicate when those changes will become effective. You are agreeing to be bound by any changes to the Privacy Policy when you use the Services after those changes become effective.
                </p>
                <h3>Questions?</h3>
                <p>
                If you have any questions or concerns regarding privacy using the Services, please send us a detailed message to: chep.xyz@gmail.com. We will make every effort to resolve your concerns.
                </p>
        ',
        'tosTitle'=>'Terms of service',
        'tos'=>'
        <cite>Last Updated: August, 2020<cite>
        <br><br>
        <p>
        Chep.xyz. (“Chep.xyz,” “we” or “our”) provides URL shortening, custom-branded link, and link management and analytics products and services to its users (collectively, the “Chep.xyz Services”). Please read these Terms of Service (the “Agreement”) carefully, as they govern your access to and use of the Chep.xyz Services and constitutes a binding legal agreement between you and Chep.xyz. If you accept this Agreement or use the Chep.xyz Services on behalf of a company or other legal entity, you represent and warrant that you have the authority to bind that company or other legal entity to the Agreement and, in such event, “you”, “your” and “Customer” will refer and apply to that company or other legal entity. If you have been granted access to and use of the Chep.xyz Services by and on behalf of the primary account holder, whether directly or through an administrator, you also agree to abide by this Agreement. In addition to this Agreement, Customer’s use of the Chep.xyz Services is governed by the Chep.xyz Privacy Policy and Chep.xyz’s DMCA Copyright Policy.
        </p>
        <p>
        YOU ACKNOWLEDGE AND AGREE THAT, BY CREATING A Chep.xyz ACCOUNT, PURCHASING A PAID ACCOUNT, OR ACCESSING OR USING THE Chep.xyz SERVICES, YOU ARE INDICATING THAT YOU HAVE READ, UNDERSTAND AND AGREE TO BE BOUND BY THESE TERMS. IF YOU DO NOT AGREE TO THESE TERMS, THEN YOU HAVE NO RIGHT TO ACCESS OR USE THE Chep.xyz SERVICES.
        </p>
        
        <p>
        THIS AGREEMENT CONTAINS AN ARBITRATION PROVISION AND CLASS ACTION WAIVER AS DESCRIBED IN THE ARBITRATION SECTION BELOW. YOU AGREE THAT DISPUTES BETWEEN US WILL BE RESOLVED BY BINDING, INDIVIDUAL ARBITRATION, AND YOU ARE WAIVING YOUR RIGHT TO A TRIAL BY JURY OR TO PARTICIPATE AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS ACTION OR REPRESENTATIVE PROCEEDING.</p>
        
        <h3>SCOPE & MODIFICATIONS</h3>
            <p>Modifications. Chep.xyz reserves the right, in its sole discretion, to modify or replace this Agreement at any time. If we modify these Terms, we will post the modification on our site or provide you with notice of the modification on your Chep.xyz Account Details page. By continuing to access or use the Chep.xyz Services after the effective date of the modification, you are indicating that you agree to be bound by the modified Agreement. Customer agrees that it is Customer’s responsibility to check this Agreement periodically for changes and that its use of the Chep.xyz Services following the posting of any changes to this Agreement constitutes acceptance of those changes. If the modified Agreement is not acceptable to you, your only recourse is to cease using the Chep.xyz Services.</p>
            <p>Scope & Current Offerings. As of the Effective Date, Chep.xyz offers certain Chep.xyz Services to Customer. Chep.xyz may add, remove, suspend, discontinue, modify or update the Chep.xyz Services at any time, at its discretion. After the effective date of such update, Chep.xyz shall bear no obligation to run, provide or support legacy versions of the Chep.xyz Services.</p>
            <p>Chep.xyz Enterprise Customers. If you have purchased a Chep.xyz Enterprise Plan, these terms may be supplemented or modified by a supplemental enterprise agreement and one or more order forms, the terms of which will control to the extent they conflict with these Terms.</p>
            <p>Support, Uptime & Training. The training and level of customer support for the tier of Chep.xyz Services you purchase is set forth on the Chep.xyz Services pricing page.</p>
        <h3>PAID ACCOUNTS</h3>
            <p>Fees. Chep.xyz offers fee-based Chep.xyz Services that provide additional features and functionality. Pricing and services for paid accounts are described on Chep.xyz’s Services pricing page and may be updated from time to time. If you sign up for a paid account, you agree to pay Chep.xyz all applicable fees for the tier of Chep.xyz Services according to your selection. Fees are non-refundable except as required by law or as otherwise specifically permitted in this Agreement.</p>
            <p>Payment. Customer will pay Chep.xyz invoices on the payment interval selected. If not otherwise specified, payments will be due immediately. Customer authorizes Chep.xyz to charge Customer for all applicable Fees using Customer’s selected payment method through Chep.xyz’s online payments platform. Customer will provide complete and accurate billing and contact information to Chep.xyz. Chep.xyz may suspend or terminate the Services if Fees are past due.</p>
            <p>Downgrades. Chep.xyz reserves the right to downgrade, suspend or terminate Customer’s access to any or all Chep.xyz Services if Fees are past due.</p>
        <h3>LICENSE, METRICS AND COMPLIANCE;</h3>
            <p>License to Chep.xyz Services. Subject to the terms and conditions of this Agreement and payment of all Fees due hereunder, Chep.xyz grants Customer, and any other party agreed in an Order Form, a limited, revocable, non-exclusive, non-sublicensable, non-transferable right and license to use the Chep.xyz Services solely to shorten uniform resource locators (“URL”), receive certain Chep.xyz Link Metrics (defined in Chep.xyz’s Privacy Policy) and, for Enterprise Plan Customers, to utilize the other products and services defined on the applicable Order Form during the Term.</p>
            <p>Chep.xyz Link Metrics. As part of the provision of Chep.xyz Services, Chep.xyz collects and generates Chep.xyz Link Metrics, which are described in Chep.xyz’s Privacy Policy. Certain, limited Chep.xyz Link Metrics are published on Chep.xyz’s website. Customer acknowledges and agrees that all Chep.xyz Link Metrics are owned by Chep.xyz, and that Chep.xyz has the right to use, license, sell or otherwise dispose of Chep.xyz Link Metrics as detailed in Chep.xyz’s Privacy Policy. Chep.xyz does not make all Chep.xyz Link Metrics available to Customer. Customer may access, use, and copy the limited Chep.xyz Link Metrics we make available to Customer according to the Customer’s service tier. Customer may not combine any Chep.xyz Link Metrics with any personally identifiable information and may not sublicense, sell, syndicate or otherwise share Chep.xyz Link Metrics with any third party.</p>
            <p>Access Credentials. Chep.xyz shall provide Customer with non-transferable access credentials for the Chep.xyz Services. Customer shall not (i) misrepresent or mask identities when using the Chep.xyz Services or seeking access credentials; (ii) select or use as a username or Branded Short Domain a name subject to any rights of a person or entity other than Customer without appropriate authorization; (iii) select or use, as Customer’s username or Branded Short Domain, a name that is otherwise offensive, vulgar or obscene; or (iv) exceed any access permitted by Chep.xyz. Customer shall safeguard all access credentials provided by Chep.xyz and shall ensure the confidentiality and security thereof. To the extent Customer is a corporate entity rather than an individual (1) only employees and contractors of Customer (“Personnel”) may use the Chep.xyz Services; (2) Customer shall require its Personnel to comply with all Laws and the use restrictions (including user seat restrictions) set out in the Agreement or otherwise prescribed by Chep.xyz and shall not share access credentials to exceed the user limitations of the service tier Customer has purchased; (3) Customer represents and warrants that its Personnel have the capacity and authority to enter into this Agreement; and (4) Customer acknowledges that it shall be fully responsible for any acts or omissions of its Personnel, whether authorized or unauthorized. Chep.xyz may update, refresh or change the manner of accessing the Chep.xyz Services in its discretion.</p>
            <p>Compliance Monitoring. Chep.xyz may monitor Customer’s use of the Chep.xyz Services for compliance with the Agreement. If Chep.xyz observes usage of the Chep.xyz Services that it believes are not in compliance with the Agreement, Chep.xyz will notify the Customer and give the Customer five (5) business days to remedy its non-compliance. If Customer does not remedy its non-compliance within five (5) business days, Chep.xyz reserves the right to suspend or terminate Customer’s use of the Chep.xyz Services. Chep.xyz reserves the right to suspend Customer’s use of the Chep.xyz Services without notice in the event that it believes, in good faith, the security of Customer’s Chep.xyz account has been compromised, or the Customer’s Chep.xyz account is being used for an unlawful purpose. And may suspend or terminate Customer’s access to the Services without notice for violation of the Agreement.</p>
        <h3>INTELLECTUAL PROPERTY & LICENSE RESTRICTIONS</h3>
            <p>Ownership. Except for any Customer Content or Customer Services, Customer acknowledges and agrees that Chep.xyz is the sole and exclusive owner of all right, title and interest in and to the Chep.xyz Services and Chep.xyz Link Metrics and all related documentation, source code, tools, scripts, processes, techniques, methodologies, inventions, know-how, concepts, formatting, arrangements, visual attributes, ideas, database rights, copyrights, patents, trade secrets, and other intellectual property, and all derivatives, enhancements, modifications and improvements thereof (“Chep.xyz Materials”). Nothing in this Agreement or any other document shall be deemed to transfer ownership of the Chep.xyz Materials. Except for the limited license rights expressly granted herein, no rights to Chep.xyz Materials are granted hereunder and all rights in such Chep.xyz Materials are reserved.</p>
            <p>Feedback. Customer is not required to provide any suggestions, enhancement requests, recommendations or other feedback regarding the Chep.xyz Services or Chep.xyz Link Metrics (“Feedback”). However, if Customer does so, all right, title and interest in and to such Feedback shall be assigned to, and shall become the sole and exclusive property of, Chep.xyz upon its creation.</p>
            <p>License Restrictions. Customer shall not share access credentials to exceed the user limitations of the service tier Customer has purchased. Customer and its Personnel shall not, and shall not permit any third party to: (i) access the Services or export data from the Services to create a service, software, documentation or data for a URL shortening service other than Chep.xyz or create shortened links or a service that is competitive with, substantially similar or confusingly similar to any aspect of the Chep.xyz Services or Chep.xyz Link Metrics; (ii) use, modify, display, perform, copy, disclose or create derivative works of the Chep.xyz Services except as expressly permitted herein; (iii) reverse engineer, decompile, disassemble, mimic, screen-scrape, frame or mirror the Chep.xyz Services or Chep.xyz Link Metrics, or use any other means to attempt to discover their source code except as expressly permitted herein; (iv) benchmark, encumber, distribute, sublicense, assign, share, sell, rent, lease, pledge or otherwise transfer the Chep.xyz Services or Chep.xyz Link Metrics to any third party; (v) transmit harmful, disabling or malicious code or devices, or infringing, defamatory, unlawful, tortious, deceptive, misleading, fraudulent, abusive, indecent or otherwise offensive content, or content that contains someone’s personal information or violates a third party’s intellectual property, privacy or publicity rights (“Prohibited Content”) through the Chep.xyz Services; (vi) access via automated or unauthorized means, interfere with, disrupt or attempt to monitor, override access or circumvent security measures for, the Chep.xyz Services or Chep.xyz Link Metrics or related systems, including via robots, spiders and other electronic methods; and (vii) obscure, remove or alter any proprietary rights or other notices on the Chep.xyz Services or Chep.xyz Link Metrics. Notwithstanding anything to the contrary herein, Chep.xyz may, in its sole discretion, immediately revoke the grant of rights set forth in Section 3 if Customer breaches or threatens to breach the restrictions in this Section or creates other security or legal concerns. Customer hereby agrees that Chep.xyz will be entitled, in addition to any other remedies available to it at law or in equity, to injunctive relief to prevent the breach or threatened breach of Customer’s obligations under this Section, without any requirement to demonstrate irreparable harm or post a bond.</p>
            <p>Technical Restrictions. Customer shall not exceed the number and/or frequency of API calls, concurrent URL shortens or other access to or use of Chep.xyz Services in the relevant documentation or as otherwise provided by Chep.xyz in an Order Form. If Chep.xyz believes that Customer has attempted to exceed or circumvent these limitations, Chep.xyz may suspend or block Customer’s access to the Chep.xyz Services. Chep.xyz may monitor Customer’s use of the Chep.xyz Services, including to ensure Customer’s compliance with this Agreement.</p>
            <p>Open Source Software. Chep.xyz Services may incorporate software that is subject to terms that, as a condition of use, copying, modification or redistribution, require such software and derivative works thereof to be disclosed or distributed in source code form, to be licensed for the purpose of making derivative works, or to be redistributed free of charge (“Open Source Software”). To the extent any Open Source Software license terms are inconsistent with this Agreement, then such rights in the applicable Open Source Software license shall take precedence over the rights granted in this Agreement, but solely with respect to such Open Source Software. Any applicable Open Source Software license is solely between Customer and the applicable licensor of the Open Source Software and Customer shall comply with the applicable Open Source Software license.</p>
            <p>Third Party Materials. Chep.xyz Services may utilize third party software or source code, including without limitation Open Source Software (“Third Party Materials”). Chep.xyz has no control over Third Party Materials. Accordingly, Chep.xyz is not responsible or liable for any Third Party Materials. While Chep.xyz has no obligation to monitor Third Party Materials, Chep.xyz may remove or modify such Third Party Materials in its discretion, including without limitation to comply with Law. Customer agrees to comply with all terms and conditions and privacy policies related to any Third Party Materials.</p>
            <p>Trademarks. Chep.xyz grants Customer a limited, revocable, non-exclusive, non-transferable, non-sublicensable license to access and use Chep.xyz’s names, logos, designs, and other trademarks incorporated into the Chep.xyz Services (“Chep.xyz Marks”) during the Term and solely for the purposes of displaying such notice as part of the Chep.xyz Services.</p>
        <h3>CUSTOMER SERVICES, CONTENT AND INFORMATION</h3>
            <p>Customer Services. Chep.xyz shall have no liability for any Customer product or service accessed through or making use of the Chep.xyz Services or any end user, customer or Personnel’s use thereof (“Customer Service”). Customer shall not use the Chep.xyz Services in any manner implying any partnership with, sponsorship by, or endorsement of the Customer Service by Chep.xyz. Customer shall not suggest or imply that Chep.xyz is the author of or otherwise responsible for the views or content of the Customer Service. The Chep.xyz Services shall not be used in connection with any Prohibited Content, or any activities where the use or failure of the Chep.xyz Services could lead to death, personal injury or property or environmental damage or adversely impact or impose liability on Chep.xyz in any manner.</p>
            Customer Content. Customer hereby grants to Chep.xyz an irrevocable, perpetual, non-exclusive, sublicensable, transferable, royalty-free, worldwide license, to use, copy, import, display, reproduce, perform, distribute, create derivative works, alter or modify all URLs and other information provided by Customer to Chep.xyz (“Customer Content”) in connection with the provision, operation and promotion of the Chep.xyz Services, creation of Chep.xyz Link Metrics and for other business purposes. Chep.xyz’s collection, use and sharing of personal information Chep.xyz receives from Customer or third parties (including social media networks) is described Chep.xyz’s Privacy Policy. As stated in our Privacy Policy, where permitted by law, if you register a Chep.xyz Account with an email address on a domain owned by an organization, such as your employer, we may share your email address and information about your Account with our sales team and the business to explore the business’ interest in creating or managing an enterprise account or for related purposes.</p>
        <h3>REPRESENTATIONS AND WARRANTIES</h3>
            <p>Chep.xyz DISCLAIMERS. Chep.xyz SERVICES ARE PROVIDED “AS IS” AND “AS AVAILABLE” WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, AND ANY WARRANTIES IMPLIED BY ANY COURSE OF PERFORMANCE OR USAGE OF TRADE, ALL OF WHICH ARE EXPRESSLY DISCLAIMED. Chep.xyz DOES NOT WARRANT THAT: (I) THE Chep.xyz SERVICES WILL BE SECURE OR AVAILABLE AT ANY PARTICULAR TIME OR LOCATION; (II) SHORTENED URLS, THE Chep.xyz SERVICES AND Chep.xyz LINK METRICS WILL BE ACCURATE, ERROR-FREE OR THAT ANY DEFECTS OR ERRORS WILL BE CORRECTED; (III) THE Chep.xyz SERVICES ARE SECURE, FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS; (IV) THE RESULTS OF USING THE Chep.xyz SERVICES OR Chep.xyz LINK METRICS WILL MEET CUSTOMER’S REQUIREMENTS OR ANY OF ITS OR ITS USERS’, PERSONNEL’S OR CUSTOMERS’ BUSINESS NEEDS; OR (V) THE Chep.xyz SERVICES WILL BE UNINTERRUPTED OR THAT ANY INTERRUPTION WILL BE CORRECTED IN A TIMELY MANNER. CUSTOMERS USE OF THE Chep.xyz SERVICES AND Chep.xyz LINK METRICS IS SOLELY AT ITS OWN RISK. FURTHER, Chep.xyz MAKES NO REPRESENTATIONS OR WARRANTIES AND SHALL ASSUME NO LIABILITY AMOUNTS OR INDEMNITY OBLIGATIONS WITH RESPECT TO ENSURING THAT CUSTOMER’S USE OF THE Chep.xyz SERVICES AND Chep.xyz LINK METRICS COMPLY WITH ANY LAWS OR REGULATIONS OUTSIDE THE UNITED STATES AND CUSTOMER SHALL BE SOLELY LIABLE FOR SUCH COMPLIANCE. Chep.xyz SHALL BEAR NO RESPONSIBILITY FOR THIRD PARTY PRODUCTS OR SERVICES (E.G., OPEN SOURCE SOFTWARE, SOCIAL MEDIA PLATFORMS, THIRD PARTY MATERIALS OR FOR HOST OR APP STORE PROVIDERS). CUSTOMER RECOGNIZES THAT THE FIGURES CONTAINED IN THE Chep.xyz LINK METRICS PRODUCED HEREUNDER ARE ESTIMATES AND MAY BE SUBJECT TO STATISTICAL ERROR. Chep.xyz DOES NOT WARRANT THAT THE Chep.xyz LINK METRICS WILL BE COMPLETELY CORRECT, ACCURATE, TIMELY OR OTHERWISE RELIABLE. Chep.xyz HEREBY DISCLAIMS ANY LIABILITY FOR ANY USE OR RELIANCE ON THE Chep.xyz LINK METRICS BY CUSTOMER AND THIRD PARTIES.</p>
        <h3>INDEMNIFICATION AND RESPONSIBILITY</h3>
            <p>Customer Indemnification. Customer will defend, indemnify and hold harmless Chep.xyz, its parents, subsidiaries, affiliates and their employees, officers, directors, representatives, contractors, customers, business partners, successors and assigns (“Chep.xyz Indemnitees”) from and against any third party claims and actions, and resulting damages, liabilities and costs (including reasonable attorneys’ fees and expenses) incurred by Chep.xyz Indemnitees arising out of or directly or indirectly related to (a) the Customer Content, Customer Services or any other Customer products and services; (b) Customer’s acts and omissions hereunder, breach of this Agreement, or violation of Laws; and/or (c) any allegation of intellectual property, privacy or publicity infringement concerning Customer Content or Customer Services. Chep.xyz shall promptly notify Customer of any claim for which it seeks indemnification; provided, however, that any delay in providing notification shall not vitiate Customer’s indemnification obligations unless Customer is materially prejudiced thereby. Customer shall have sole control over the defense of any claim under this Section, except that Chep.xyz may approve any counsel used by Customer and that Chep.xyz may participate in the defense, at Customer’s cost. All settlements of indemnification claims require the consent of Chep.xyz</p>
        <h3>TERM AND TERMINATION</h3>
            <p>Agreement Term. This Agreement shall commence on the date the Customer accepts this Agreement by creating an account or purchasing a paid service tier (“Effective Date”) and remain in effect for the duration of the term selected by Customer, unless otherwise terminated as permitted herein (“Initial Term”). If your paid account is set to automatically renew, please see section 2(B) above for the auto-renewal terms.
            Right to Terminate. Chep.xyz may terminate this Agreement immediately in its discretion. Upon expiration or termination of this Agreement, all applicable rights and access granted to Customer shall automatically terminate and Customer and its Personnel shall cease any further use of the Chep.xyz Services and return, or, if directed by Chep.xyz, destroy, all Confidential Information of Chep.xyz. Any Section of this Agreement which by its nature would survive such expiration or termination shall so survive.</p>
        
        <p>Contacting Chep.xyz. If you have any questions about these Terms, please contact us at chep.xyz@gmail.com
        ',
    ];
?>